.ubuntu: &ubuntu
  image: crondaemon/wireshark
  retry: 1
  before_script:
    - rm -rf /etc/apt/sources.list.d/*
    - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main" > /etc/apt/sources.list.d/clang.list
    - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main" > /etc/apt/sources.list.d/clang6.list
    - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main" > /etc/apt/sources.list.d/clang7.list
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
    - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" > /etc/apt/sources.list.d/gcc.list
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1E9377A2BA9EF27F
    - apt-get update -qq
    - mkdir build
    - cd build
gcc-4:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build gcc-4.9 g++-4.9 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 ..
    - ninja
gcc-5:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build gcc-5 g++-5 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 ..
    - ninja
gcc-6:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build gcc-6 g++-6 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 ..
    - ninja
gcc-7:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build gcc-7 g++-7 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 ..
    - ninja
gcc-8:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build gcc-8 g++-8 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ..
    - ninja
gcc-8-nopcap:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build gcc-8 g++-8 -y
    - cmake -GNinja -DENABLE_PCAP=OFF -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ..
    - ninja
clang-5:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build clang-5.0 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=clang-5.0 -DCMAKE_CXX_COMPILER=clang++-5.0 -DCMAKE_C_FLAGS=-Wframe-larger-than=20000 ..
    - ninja
clang-6:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build clang-6.0 -y
    - cmake -GNinja -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DCMAKE_C_FLAGS=-Wframe-larger-than=20000 ..
    - ninja
clang-7:
  <<: *ubuntu
  script:
     - ../tools/debian-setup.sh --install-optional ninja-build clang-7 -y
     - cmake -GNinja -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7 -DCMAKE_C_FLAGS=-Wframe-larger-than=20000 ..
     - ninja
clang-7-nopcap:
  <<: *ubuntu
  script:
    - ../tools/debian-setup.sh --install-optional ninja-build clang-7 -y
    - cmake -GNinja -DENABLE_PCAP=OFF -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7 -DCMAKE_C_FLAGS=-Wframe-larger-than=20000 ..
    - ninja
rpm-centos-7:
  image: centos:7
  script:
    - yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - yum install -y which
    - tools/rpm-setup.sh --install-optional -y
    - mkdir build
    - cd build
    - cmake3 -GNinja ..
    - ninja-build
    - ninja-build rpm-package
rpm-opensuse-42.3:
  image: opensuse:42.3
  script:
    - zypper --non-interactive install which update-desktop-files
    - tools/rpm-setup.sh --install-optional
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make rpm-package
rpm-fedora-28:
  image: fedora:28
  script:
    - yum install -y which
    - tools/rpm-setup.sh --install-optional -y
    - mkdir build
    - cd build
    - cmake3 -GNinja ..
    - ninja-build
    - ninja-build rpm-package
after_script:
  - if [ -f build/run/tshark ];then build/run/tshark --version; fi
