language: cpp
sudo: required
dist: trusty
os:
  - osx
  - linux
compiler:
  - clang
  - gcc
env:
 - CMAKE_OPTS="-DENABLE_PCAP=ON"
 - CMAKE_OPTS="-DENABLE_PCAP=OFF"
matrix:
  exclude:
  # Exclude gcc build (Need some work) with osx
  - os: osx
    compiler: gcc
before_install:
  - echo $TRAVIS_OS_NAME
  - $CC --version
  # macos
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./tools/macos-setup-brew.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then PATH=/usr/local/opt/qt5/bin:$PATH; fi
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  # libstdc++-4.8 is needed by Clang to build
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install libstdc++-4.8-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ./tools/debian-setup.sh --install-optional -qq; fi
  - $CC --version
before_script:
  - sudo gem install asciidoctor
  - mkdir build
  - cd build
  - cmake -GNinja ${CMAKE_OPTS} ..
script:
  - ninja
