name: Build Windows

on: [push]

jobs:
  windows:
    name: Build & Test
    runs-on: windows-2022
    env:
      PLATFORM: x64
      WIRESHARK_BASE_DIR: C:\Development
      CMAKE_PREFIX_PATH: D:\a\wireshark\Qt\6.8.3\msvc2022_64
      WIRESHARK_VERSION_EXTRA: -GithubActionBuild
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Choco install
        run: choco install -y --force --no-progress asciidoctorj xsltproc docbook-bundle nsis winflexbison3 cmake
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          arch: win64_msvc2022_64
          version: 6.8.3
          modules: 'qt5compat'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 17.13
      - name: Set MSVC command prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Mkdir
        run: mkdir build
      - name: Cmake
        run: cmake -DCMAKE_SYSTEM_VERSION="10.0.20348.0" -G "Visual Studio 17 2022" -A x64 ..
        env:
          PLATFORM: x64
          WIRESHARK_BASE_DIR: C:/wireshark-libs
        working-directory: build
      - name: Build
        run: cmake --build . --config RelWithDebInfo
        working-directory: build
      - name: Build guides
        run: cmake --build . --config RelWithDebInfo --target user_guide_html
        working-directory: build
      - name: Build test-programs
        run: cmake --build . --config RelWithDebInfo --target test-programs
        working-directory: build
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install pytest
        run: pip install pytest pytest-xdist
      - name: Run tests
        run: pytest
        working-directory: build
      - name: Build Windows pkg
        run: |
          msbuild /m /p:Configuration=RelWithDebInfo wireshark_nsis_prep.vcxproj
          msbuild /m /p:Configuration=RelWithDebInfo wireshark_nsis.vcxproj
        working-directory: build
      - name: Upload Windows packages
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: build/packaging/nsis/*exe
